name: desafio_rickandmorty
description: "Rick and Morty - Flutter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get_it: ^8.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4



flutter:
  uses-material-design: true


  assets:
    - assets/logos/


  fonts:
  - family: Outfit
    fonts:
      - asset: assets/fonts/Outfit-Regular.ttf
        weight: 400
      - asset: assets/fonts/Outfit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Outfit-Bold.ttf
        weight: 700



flutter_native_splash:
  android: true
  ios: true

  color: "#81c339"
  image: assets/logos/splash.png

  android_12:
    color: "#81c339"
    image: assets/logos/splash.png
    icon_background_color: "#81c339"